### ISSUE TITLE
Can not Deploy Heroku 

### ISSUE THREAD

**Issue by kendyhikaru** [salesforce/vulnreport#1]
When deploy new app, i get error:
The account "xxxxxxxxxxxxx is not permitted to install the sendgrid add-on at this time. If you believe this is an error please contact support and reference ID fd70d7e3-05c9-4e0a-9c51-341f1334b2b8 when opening an ticket.
Please help me fix

**Comment by tbach** [comment]
Hi kendyhikaru,

This is a Heroku Account issue, not an issue with the Vulnreport code. Please contact Heroku support to see why your account cannot use Sendgrid.

If Sendgrid is an impossibility, you can manually deploy the code to Heroku and ignore the sendgrid requirement. Note that you will not be able to send emails from Vulnreport (used for password reset, etc.) without Sendgrid unless you set the code up to use another library.
