### ISSUE TITLE
Installation/deployment is broken

### ISSUE THREAD

**Issue by putsi** [salesforce/vulnreport#14]
I'm having a hard time getting the app installed.
When deploying to Heroku, the deployment fails with error:

```
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.1.2
-----> Installing dependencies using bundler 1.13.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Your Ruby version is 2.1.2, but your Gemfile specified > 2.1.2
       Bundler Output: Your Ruby version is 2.1.2, but your Gemfile specified > 2.1.2
 !
 !     Failed to install gems via Bundler.
 !     Detected a mismatch between your Ruby version installed and
 !     Ruby version specified in Gemfile or Gemfile.lock:
 !     https://devcenter.heroku.com/articles/ruby-versions#your-ruby-version-is-x-but-your-gemfile-specified-y
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

When I try to install it on a local Ubuntu 16.04 server, the same Ruby version error is shown. That can be "fixed" by removing the 'ruby "> 2.1.2"'-line from the Gemfile. However after that, the "bundle install"-command fails because postgres-related gems cannot be compiled.

**Comment by tbach** [comment]
@putsi sorry about that. I have pulled a fix in to master and tested the Heroku deploy, should be working now.

**Comment by putsi** [comment]
Thanks for the fast response!
The Heroku deployment works now for me also. 
The postgres-gems were also now installed properly on local Ubuntu installation.
