### ISSUE TITLE
Issue while running bundle install

### ISSUE THREAD

**Issue by sanjogpandasp** [salesforce/vulnreport#17]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170223-57657-1d6ucazdo_postgres-0.10.17/gems/do_postgres-0.10.17/ext/do_postgres
/usr/bin/ruby2.3 -r ./siteconf20170223-57657-1upehkp.rb extconf.rb
checking for main() in -lpq... yes
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for postgres.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-pgsql-server-dir
	--without-pgsql-server-dir
	--with-pgsql-server-include
	--without-pgsql-server-include=${pgsql-server-dir}/include
	--with-pgsql-server-lib
	--without-pgsql-server-lib=${pgsql-server-dir}/lib
	--with-pgsql-client-dir
	--without-pgsql-client-dir
	--with-pgsql-client-include
	--without-pgsql-client-include=${pgsql-client-dir}/include
	--with-pgsql-client-lib
	--without-pgsql-client-lib=${pgsql-client-dir}/lib
	--with-pqlib
	--without-pqlib
Could not find PostgreSQL build environment (libraries & headers): Makefile not created

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20170223-57657-1d6ucazdo_postgres-0.10.17/extensions/x86_64-linux/2.3.0/do_postgres-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20170223-57657-1d6ucazdo_postgres-0.10.17/gems/do_postgres-0.10.17 for inspection.
Results logged to /tmp/bundler20170223-57657-1d6ucazdo_postgres-0.10.17/extensions/x86_64-linux/2.3.0/do_postgres-0.10.17/gem_make.out

**Comment by tbach** [comment]
This is definitely a problem building the postgres gem, so unfortunately not something I'll be able to help with. Without doing research my guess is that it has to do with trying to build do_postgres 0.10.17 with ruby 2.3.x.

The ruby specified in the gemfile (2.1.2) builds correctly with a clean clone of this repo or a deploy to Heroku. As noted in #16 I'll check 2.1.5 next week and potentially update the repo to that.

**Comment by sanjogpandasp** [comment]
Thanks 

Let me create an venv with ruby version 2.1.2 and try install within that env. Hope that should work. Also I will try to make a Docker file out of it, which will ease up the process :)

**Comment by rubyautomation** [comment]
If you run into this issue again, try looking at the log.  Usually it tries a server directory with the version.

On Ubuntu 16.04 LTS, I checked out the log and found postgres 9.5.

sudo apt-get install postgres-server-dev-9.5 worked for me, then sudo gem install do_postgres worked just fine.

**Comment by noraj** [comment]
see #32 also

> I'm using rbenv instead of rvm but I can't compile ruby 2.1.2 because it is too old, also ruby 2.1.2 support is totally dropped and do not receive security fix even for critical vulns. So a massive upgrade is required. See #32
