### ISSUE TITLE
Change export view to PDF

### ISSUE THREAD

**Issue by munchkinboy1991** [salesforce/vulnreport#18]
Hi @tbach -- Quick question, I will like to change the "Download" function to PDF rather than web browser version. Would you be able to direct me where can I find that snippet?

**Comment by tbach** [comment]
@munchkinboy1991 If you enable the PDF export option a PDF link will appear on test view which will open the PDF output. Right click/save as on that link or opening it and saving it would save a PDF.

In your individual installation if you wanted to reallocate the "Download" link to the PDF version you would want to edit around

https://github.com/salesforce/vulnreport/blob/master/views/test_single.erb#L301

**Comment by munchkinboy1991** [comment]
Thanks @tbach ! Sorry one more question: how can I properly create separate lines in the contents field? 

how it looks now:
![image](https://cloud.githubusercontent.com/assets/25827516/23963410/906182e4-0987-11e7-83d7-4563c91e0d11.png)

how I want it to look:
![image](https://cloud.githubusercontent.com/assets/25827516/23963424/a073a7a2-0987-11e7-918f-d733e5c6de6f.png)

**Comment by munchkinboy1991** [comment]
Great thanks! @tbach
