### ISSUE TITLE
How to import XML data

### ISSUE THREAD

**Issue by sekirkity** [salesforce/vulnreport#2]
Hi there, I am trying to import XML data from a report generated by OWASP ZAP, but am unable to do so successfully. When I try I am returned to the Test page with no changes. I wasn't able to find anything in the documentation about XML importing, could you please offer some guidance, thanks!

**Comment by tbach** [comment]
Hi chopteeth,

I'll update the repo with documentation about the XML format we currently use, likely tomorrow.

I'll be adding a backlog item to add full support for ZAP XML output as well, as it is not currently parsed by Vulnreport but I think thats a great idea.

**Comment by tbach** [comment]
Chopteeth - I've pushed basic documentation about the current limited XML support. I have an existing backlog item which I will continue to work on for supporting ZAP and Burp XML, as well as a more abstract import/export XML feature for Vulnreport-to-Vulnreport.

Thanks!

**Comment by sekirkity** [comment]
Thanks!! This is much appreciated :)

**Comment by mogul** [comment]
@tbach: 

> I have an existing backlog item which I will continue to work on for supporting ZAP and Burp XML, as well as a more abstract import/export XML feature for Vulnreport-to-Vulnreport.

Is there anywhere that we can follow/participate in the progress of this work? OWASP ZAP import in particular would be immediately useful for us.

**Comment by tbach** [comment]
@mogul I'll open up an issue on Github so you can track it to completion. I am expecting this work to be done over the next couple of weeks based on my availability.

It is the top item on the backlog after the 3.0.2 release which I just tagged/pushed.

(This is now open as issue #3 )
