### ISSUE TITLE
Error when open Settings/VR Settings/Cache Settings

### ISSUE THREAD

**Issue by fastfire** [salesforce/vulnreport#20]
When open menu Settings/VR Settings/Cache Settings, I receive this error:

SocketError at /admin/settings/cache
getaddrinfo: Temporary failure in name resolution

    file: ruby.rb location: getaddrinfo line: 177

**Comment by tbach** [comment]
Do you have a Redis db set up and pointed to by ENV['REDIS_URL']?

If so, can you post the full stack trace?

**Comment by fastfire** [comment]
Yes, my .env file contain this:

export REDIS_URL=redis://locathost:6379

And there was a typo mistake ('locathost')! I corrected this and now it is working! Sorry!

Thank you tbach!

**Comment by tbach** [comment]
Great!
