### ISSUE TITLE
json conflicts

### ISSUE THREAD

**Issue by fastfire** [salesforce/vulnreport#21]
I'm installed wpscan, with json version 2.1.0. Non, when I try to start Vulnreport, receive this error:

./start.sh 
Using rack adapter
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2286:in `raise_if_conflicts': Unable to activate activesupport-4.2.6, because json-2.1.0 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::ConflictError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/system/Documenti/pentest/vulnreport/web.rb:26:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/system/Documenti/pentest/vulnreport/config.ru:8:in `block in <main>'
	from /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/system/Documenti/pentest/vulnreport/config.ru:1:in `new'
	from /home/system/Documenti/pentest/vulnreport/config.ru:1:in `<main>'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:42:in `for'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:170:in `load_adapter'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:74:in `start'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
	from /var/lib/gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	from /usr/local/bin/thin:23:in `load'
	from /usr/local/bin/thin:23:in `<main>'

Here my Gemfile:

source 'https://rubygems.org'

ruby '2.3.1'

gem "sinatra", '~> 1.4.6'
gem "thin", '~> 1.6.4'
gem "data_mapper", '~> 1.2.0'
gem "dm-postgres-adapter", '~> 1.2.0'
gem "ruby-saml", "~> 1.0.0"
gem "chronic", '~> 0.10.2'
gem "savon", '~> 2.11.1'
gem "rubyzip", '~> 1.2.0'
gem "nokogiri", '~> 1.6.7.2'
gem "activesupport"
gem "redis", '~> 3.3.0'
gem "json", '~> 1.8.3'
gem "rack_csrf", '~> 2.5.0'
gem "rack-ssl", '~> 1.4.1'
gem "rufus-scheduler", '~> 3.2.0'
gem 'pony', '~> 1.11'
gem 'multipart-post', '~> 2.0.0'
gem 'pg', '~> 0.18.4'
gem 'rforce', '~> 0.13'
gem 'xml-simple', '~> 1.1.5'
gem 'httparty', '~> 0.13.7'
gem "dotenv", '~> 2.1.1'
gem 'rollbar', '~> 2.10.0'
gem 'yard', '0.8.7.6'
gem 'yard-dm', '0.1.1'
gem 'yard-sinatra', '1.0.0'
gem 'eventmachine', '1.0.7'
gem "wkhtmltopdf-heroku"
gem "pdfkit", '~> 0.8.2'

**Comment by fastfire** [comment]
Workaround with 'sudo gem uninstall json -v 2.1.0'. There is another possible to have vulnreport working with json 2.1.0 installed?

Thank you.

**Comment by littledatas** [comment]
This is extremely late. Apologies but getting this resolved just in case somebody else runs into this issue.

This is a won't fix because you can use RVM (rvm.io) to manage your ruby environments. I recommend you do that to avoid any conflicts between ruby gems.

**Comment by noraj** [comment]
> This is a won't fix because you can use RVM (rvm.io) to manage your ruby environments. I recommend you do that to avoid any conflicts between ruby gems.

@littledatas I do not agree. I'm using [rbenv](https://github.com/rbenv/rbenv/wiki/Why-rbenv%3F) instead of rvm but I can't compile ruby 2.1.2 because it is too old, also ruby 2.1.2 support is totally dropped and do not receive security fix even for critical vulns. So a massive upgrade is required. See #32

**Comment by littledatas** [comment]
Hey @noraj,

Thanks for working on that PR. Unfortunately, I'm no longer a maintainer for this project and don't know the status on updates from the Salesforce team.

Thanks!
