### ISSUE TITLE
Website is not loaded properly

### ISSUE THREAD

**Issue by seabaz** [salesforce/vulnreport#22]
Hi,

Managed to run the SEED file and vulnreport has already been seeded. However, the website on the configured port (in start.sh) is not loaded. E. https://localhost:8443/
Got some error logs after running start.sh, 
Using rack adapter
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2287:in `raise_if_conflicts': Unable to activate activesupport-4.2.6, because json-2.0.1 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::ConflictError)
...

Can you advise me please? thanks

**Comment by littledatas** [comment]
The version of ruby that is currently supported is 2.1.2. It looks like you are running ruby 2.3.0. We are looking at using a more modern version of ruby, but until then, please use ruby 2.1.2.
