### ISSUE TITLE
Rack::Csrf::InvalidCsrfToken at /login 

### ISSUE THREAD

**Issue by bug-vulnreport** [salesforce/vulnreport#23]
Hi,

I've installed VR in Ubuntu 16.04.03 with no issues. But this time, i got invalid csrf token error. I have no clue whats going on here and i cannot login to the dashboard. Could you please help me?

![screenshot 8](https://user-images.githubusercontent.com/30976255/29249185-8e5b839e-805d-11e7-93c1-ec34b4e2289d.png)
![screenshot 9](https://user-images.githubusercontent.com/30976255/29249187-8e671466-805d-11e7-9de5-38c7019d13bb.png)
![screenshot 10](https://user-images.githubusercontent.com/30976255/29249188-8e6801e6-805d-11e7-85b7-365c28b012aa.png)
![screenshot 11](https://user-images.githubusercontent.com/30976255/29249189-8e684782-805d-11e7-9ce8-c9383c0b5531.png)
![screenshot 12](https://user-images.githubusercontent.com/30976255/29249186-8e655cfc-805d-11e7-8626-286b800566f5.png)
![screenshot 13](https://user-images.githubusercontent.com/30976255/29249190-8e685060-805d-11e7-912f-705b27fb881f.png)

**Comment by littledatas** [comment]
Can you post the error log file from the server? I've not seen this error before.

Did you seed the database first using SEED.rb?

**Comment by littledatas** [comment]
I haven't heard back in a while so I'm going to close this issue. If you still need help, feel free to reopen.
