### ISSUE TITLE
Add another section when creating a report?

### ISSUE THREAD

**Issue by munchkinboy1991** [salesforce/vulnreport#25]
Hi, 
I have received feedback from external teams that there isn't a precise section for "Scope" which will include the URL and user ID's my team used to complete the security assessment. Any suggestions you may have how I can add a section for "Scope" when creating a report?

See screenshot (my idea (if possible) is to add the "scope" in one of those sections as we fill out the information):
![screen shot 2017-11-14 at 3 36 54 pm](https://user-images.githubusercontent.com/25827516/32803528-c646d2a8-c951-11e7-9cfd-7e74add3eabc.png)

**Comment by munchkinboy1991** [comment]
@tbach

**Comment by littledatas** [comment]
Sorry for the delayed response @munchkinboy1991 

Your best option is creating a VRLO (Vulnreport Linked Object) which can be added to both the Application and Test views. 

See http://vulnreport.io/documentation and scroll down to the 'Custom Interfaces' section. This should have some documentation on how to add this yourself. 

You can also create sections on the individual vulns themselves for URL and user ID if you only want certain vulns to have this data. This would then be configurable through the admin interface.

See here for the section code: https://github.com/salesforce/vulnreport/blob/master/models/section.rb

Let me know if any of these do or don't work for you or if you need some more help.

**Comment by littledatas** [comment]
Going to go ahead and close this @munchkinboy1991 . If you still need help, please feel free to re-open.
