### ISSUE TITLE
I don't set up database when I run SEED.rb

### ISSUE THREAD

**Issue by ThuyNT2916** [salesforce/vulnreport#5]
I try build app. I create _.env_:

> export RACK_ENV=production
> export VR_SESSION_SECRET=123456
> export DATABASE_URL=postgres://admin:123456@127.0.0.1:5432
> export REDIS_URL=redis://:123456@127.0.0.1:6379/16
> export ROLLBAR_ACCESS_TOKEN=hgfsdhfjy87efhsnbf78wrenfd87ew79
> Next, I run _bundle install_ successfully. But I run SEED.rb, it display notice error:
> ![seed](https://cloud.githubusercontent.com/assets/10936898/18698712/88d284e4-7ff6-11e6-8953-0759a39af321.png)
> In DB, I have created user _admin_ before.
> Can you help me to fix this error? Or give me mistake!
> Thank you!

**Comment by tbach** [comment]
Hi Thuy,

You need to create a database, not just a Postgres user. This error is being caused by Vulnreport's seed script not having a database to use.

When you do that, your DATABASE_URL should be of the form:
postgres://[USER]:[PASS]@[HOST]/[DB NAME].

**Comment by ThuyNT2916** [comment]
I understand my mistake. Thank you very much! :)

**Comment by ThuyNT2916** [comment]
Sorry!!
I setup VulnReport App on local, don't use Heroku to deploy.
I have finished step 2 , it done. I try to open app on  web browser, it doesn't display. 
I read about Sinatra and I try to run file _web.rb_, but it displays
![sinatra](https://cloud.githubusercontent.com/assets/10936898/18704586/b880005e-8014-11e6-82da-7649eaed15c9.png)
And I still don't open web.
Can you guide me how to continue!
Where is my mistake?

**Comment by tbach** [comment]
@ThuyNT2916 below the lines that you screenshotted will be a line like 

```
Maximum connections set to 1024
Listening on 0.0.0.0:443, CTRL+C to stop
```

That is the host/port you'll need to access to view Vulnreport.

**Comment by ThuyNT2916** [comment]
After step 2, I need run app by using Sinatra, by command **ruby web.rb**, Is this true?
I'm trying run app by command **ruby web.rb** in Vulnreport folder, but I can't run it. Any thing is not enable. Host:port listening doesn't appear. 
I use netstat, I don't see app running
I'm using Ruby version 2.3.1

**Comment by tbach** [comment]
No, you should run it using `thin start`. See the file in the repo `start.sh` for an example of how it can be invoked, though if you are not using `authbind` locally you could probably get it going with just `thin start`.

**Comment by tbach** [comment]
Another good example of how to start it is in `Procfile`:

`web: bundle exec thin start -p $PORT --threaded`

**Comment by ThuyNT2916** [comment]
I have done App on local. Thank for your instruction!
